### ISSUE TITLE
Control of spotify from homeassistant

### ISSUE THREAD

**Issue by Apurv505** [hassio-addons/addon-spotify-connect#101]
# Problem/Motivation
Is there a way to control  Spotify connect from the Home assistant dashboard? Like pause when motion is not detected by room PIR sensor and resume when it does.
> (Why the issue was filed)
Hoping that this could be included in the next release.
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Yes, but is has nothing to do with this add-on. Please check the Home Assistant documentation instead 👍
