### ISSUE TITLE
Feature request: Entity for Spotify Connect status

### ISSUE THREAD

**Issue by LC7894** [hassio-addons/addon-spotify-connect#107]
## Problem/Motivation

I am running the addon on a Pi that is connected via Cinch with my (dumb and old) audio receiver which I control via Broadlink/IR. When I choose Home Assistant as a playing target in the Spotify app it takes up to 30 seconds until the official Spotify integration status changes from `idle` to `playing`. The status change then triggers Broadlink to send some IR commands to turn on my receiver and change the Input to Home Assistant.

## Expected behavior

After choosing Home Assistant as source and hitting play in the Spotify app, it should take just a few seconds to turn on the receiver.

## Actual behavior

With the limitation of the 30 seconds update interval of the Spotify integration my receiver needs around 30 seconds (worst case) until it turns on - this is too long in my eyes.

## Steps to reproduce

1. Install the Spotify integration and the Spotify connect addon. 
2. Connect an audio receiver that you can turn on by IR or some other kind of automation
3. Write an automation that turns on the receiver when the status of the Spotify integration changes from `idle` to `playing`.
4. Open the Spotify app, choose Home Assistant as playing target and start playing music
5. Wait until the receiver turns on and you hear the music.
6. Stop the music, turn the receiver off again
7. Repeat steps 4-6 several times to experience the effect of the 30seconds update interval of the Spotify integration (sometimes it should take just a few seconds until the receiver turns on, sometimes it should take up to 30 seconds - depending on the duration until the next update of the integration).

## Proposed changes

As I read in the forum it is not advised to shorten the update interval of the Spotify integration. So it is not possible to have a faster status change from `idle` to `playing` triggered by the integration. Because of this reason I am requesting a change for the Spotify connect addon. It would be amazing if the addon would provide a basic entity that shows the status of the Spotify Connect addon (`playing`/`idle` would be enough). By this entity, audio receivers that are directly connected to the computer Home Assistant is running on, can be turned on significantly faster.

An entity like this has already been implemented in an unofficial addon made by @giannello. I tested it over several months and it worked very reliable - my receiver turned on instantly after starting to play music via the Spotify app. No more delays and no girlfriend that starts to make jokes about how long it takes to turn on the receiver - great! 😃

**Comment by LC7894** [comment]
Thank you for the quick reply and the additional reading material. I understand that being consistent here is very important. Let's hope there will be a way to receive faster updates from the Spotify integration in the future then. For the described problem the Spotify integration is not optimal. At the moment I see no other way to get rid of the above mentioned delay without providing an entity by the Spotify Connect addon.

**Comment by LC7894** [comment]
> This is an add-on, not an integration.
> External things should not provide entities.
> 
> Additional reading material: https://www.home-assistant.io/blog/2021/05/12/integrations-api/

Thank you for the quick reply and the additional reading material. I understand that being consistent here is very important. Let's hope there will be a way to receive faster updates from the Spotify integration in the future then. For the described problem the Spotify integration is not optimal. At the moment I see no other way to get rid of the above mentioned delay without providing an entity by the Spotify Connect addon.

**Comment by frenck** [comment]
We don't make the API in this case, Spotify does.

**Comment by DaAwesomeP** [comment]
For anyone finding this issue later, I have implemented LibreSpot's event handler (already present in the LibreSpot CLI) in my fork: https://github.com/DaAwesomeP/ha-addon-spotify-connect-advanced

It works similar to the way the events work in the NUT addon; it sends a `spotify_advanced.event` to Home Assistant Core whenever it changes state, volume, etc.
