### ISSUE TITLE
DAC Support?

### ISSUE THREAD

**Issue by spencerthayer** [hassio-addons/addon-spotify-connect#110]
Does Hassio support USB DAC's yet? Or is this [closed ticket](https://github.com/hassio-addons/addon-spotify-connect/issues/49) still the official answer? That Home Assistant does not support non-pi audio devices.

**Comment by frenck** [comment]
The add-on doesn't care. If the OS supports it, the addon can use it.

Please note that Hassio doesn't exists as a term anymore. It is ambiguous.

**Comment by spencerthayer** [comment]
Do you know if the Home Assistant OS supports USB DACs?

**Comment by frenck** [comment]
I don't
