### ISSUE TITLE
Add support for custom CLI advanced options

### ISSUE THREAD

**Issue by DaAwesomeP** [hassio-addons/addon-spotify-connect#111]
# Problem/Motivation

There are a lot more advanced options for librespot that advanced users may wish to make use of: https://github.com/librespot-org/librespot/wiki/Options

## Proposed changes

Adding an additional advanced option (so that it is hidden by default) for user-provided additional command line options. There are so many options that it does not seem maintainable to provide a direct UI option for each. Since these options are advanced, they would be at the user's own risk.

I suppose a custom CLI options field would also allow for overriding the preset options, but that could either be left as an at-your-own risk feature or filtered out with regex.

**Comment by frenck** [comment]
If you need those options, this add-on is not for you.

**Comment by DaAwesomeP** [comment]
For anyone who finds this issue in the future, I have implemented this feature in my fork (as well as events from LibreSpot): https://github.com/DaAwesomeP/ha-addon-spotify-connect-advanced
