### ISSUE TITLE
Add in works with only premium account

### ISSUE THREAD

**Issue by mohankrishna-g** [hassio-addons/addon-spotify-connect#118]
![Screenshot_20210623-234500](https://user-images.githubusercontent.com/62322435/123147797-1861df80-d47d-11eb-939d-c4054252a45e.jpg)
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mohankrishna-g** [comment]
Tried this add on but showing this.

**Comment by frenck** [comment]
That is correct, which is documented as well

![image](https://user-images.githubusercontent.com/195327/123148213-3ff67f00-d460-11eb-85d9-11fef2b3858c.png)
