### ISSUE TITLE
Since v0.10.0 playback always starts at maximum volume.

### ISSUE THREAD

**Issue by spudje** [hassio-addons/addon-spotify-connect#154]
# Problem/Motivation

I recently updated to v0.10.0. Before that the addon worked fine. Since v0.10.0 everytime when I "Spotify Connect" and start playing music, the volume is set to maximum.

## Expected behavior

Behaviour as before. Remember the volume it was set to at the end of a previous Spotify Connect session and use that as starting volume for new session.

## Actual behavior

See motivation.

## Steps to reproduce

1. "Spotify Connect" to the the addon.
2. Start playing music in Spotify app
3. Music plays at maximum volume

## Proposed changes

Revert to volume behaviour of previous version.

**Comment by kiclaw** [comment]
I have the same issue, Is there any way to fix it?
