### ISSUE TITLE
Is there a way to increase the volume?

### ISSUE THREAD

**Issue by jperry1234** [hassio-addons/addon-spotify-connect#155]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jperry1234** [comment]
Is there a way to increase the volume?

**Comment by Gadzhi13** [comment]
Hi!
If you are using your smartphone, for example, to connect to the spotify add-on you can change volume from that smartphone.

**Comment by JayNutZ** [comment]
There are services for `media_player.volume_set` and `media_player.volume_up`
