### ISSUE TITLE
Music cutting out

### ISSUE THREAD

**Issue by Yersi88** [hassio-addons/addon-spotify-connect#156]
# Problem/Motivation

> Unexpected behavior. 

## Expected behavior

> Music plays without interruption.

## Actual behavior

> Music "pauses" constantly. Music plays than stops for second or so and resumes, this happens roughly every minute. 

## Steps to reproduce

> No idea, it just happens. I tired different bitrates doesn't seem to have effect on it. Not sure what else to try

**Comment by Gadzhi13** [comment]
Hi!
Have you taken a look into the logs?
