### ISSUE TITLE
Keep alive

### ISSUE THREAD

**Issue by JayNutZ** [hassio-addons/addon-spotify-connect#159]
Hey there!
First of all, thank you for your great work!

# Problem/Motivation
I am currently realizing a alarm clock in home assistant with spotify as my choice for the sound. Now I have a wired speaker directly connected to the raspberry pi where hass.io is running on. This is running really good, even got a rough fade-in effect working.
The Problem is now, that this spotify player is getting unavailable for some reason over time. Meaning, i get the toast `no active playback device` when i need it. In my automation I already try selecting the source/output before playing. Works as well when this extension is active

## Expected behavior
Player/Spotify service getting idle but can be "awakened" by home assistant.
In the official spotify app I can find the "Home Assistant" device and I am able to wake it up.

## Actual behavior
Spotify cant wake up directly via home assistant.
Is there a option I am missing for a better standby?
Do I need a better string value for source/output as "Home Assistant" (named still this way), maybe a Id?
No logs giving a hint.

## Steps to reproduce
Wait some hours

## Proposed changes
A clear documented way to wake this addon up, like in the spotify app

**Comment by quiqueck** [comment]
I have the same issue. Also tried to use the ID I got from the spotify dev-dashboard, but that did not help either.
