### ISSUE TITLE
Doest not work with latest ha&hacs version

### ISSUE THREAD

**Issue by fryc88** [hassio-addons/addon-spotify-connect#162]
# Problem/Motivation

> Not possible to find in HACS repo, won't add manually

## Expected behavior

> search, add and use

## Actual behavior

> Gives error when trying to integrate it via repo link: https://github.com/hassio-addons/addon-spotify-connect
![obraz](https://user-images.githubusercontent.com/50572708/148064128-54584d94-7b7d-4bff-8dc7-9e6940f9ab7d.png)

## Steps to reproduce

> Paste repo link to HACS > add custom repository

**Comment by frenck** [comment]
This is an add-on...

HACS doesn't do add-ons, HACS does integrations...

integrations are not add-ons...
