### ISSUE TITLE
Devices

### ISSUE THREAD

**Issue by h3ld3rkid** [hassio-addons/addon-spotify-connect#189]
Hello, i'm facing a problem with Spotify addon. After update HA to last version the addon left to work... 
My account its connected but in card on lovelace when i try configure my devices appears ( google nest and mini) but when i save the card says loading and in devices says " no devices found"

Someone have any idea? I can post images if needed

Thnkx

**Comment by frenck** [comment]
> My account its connected but in card on lovelace when i try configure my devices appears ( google nest and mini) but when i save the card says loading and in devices says " no devices found"

The Spotify Connect add-on has nothing to do with Home Assistant cards or integrations. I think you are mixing things up.

../Frenck

**Comment by h3ld3rkid** [comment]
Sorry! I thought that i post the issue in card page!!! Sorry

**Comment by frenck** [comment]
Don't worry about it 👍 

../Frenck
