### ISSUE TITLE
No sound - RasPi 3b+

### ISSUE THREAD

**Issue by timelf123** [hassio-addons/addon-spotify-connect#19]
# Problem/Motivation

> No sound plays despite spotify connect getting track information. I have confirmed my speakers are working. This ticket is identical to https://github.com/hassio-addons/addon-spotify-connect/issues/6 in every way - there was just no way to necro it since it was closed as stale

**Comment by timelf123** [comment]
A few reboots later and this seems to be working

**Comment by frenck** [comment]
👍
