### ISSUE TITLE
USB audio output improvement

### ISSUE THREAD

**Issue by nikogusm** [hassio-addons/addon-spotify-connect#196]
hello, thanks for your addon, it works perfectly.

I notice you an improvement that could be done by adding on the output setting also the USB outputs like external audio cards.

Actually there is a workaround that lets you add a usb sound card as output setting it as default audio card of home assistant system, and after you added it like that in the terminal you can see it in the Spotify connect audio output setting.

if you want you can check in this link how an user solved it and if you can improve the integration adding this by default it should be nice: https://community.home-assistant.io/t/selecting-default-soundcard/278766/6?u=nikogu

thank you so much for the attention

<img width="359" alt="Screenshot 2022-11-13 alle 02 15 19" src="https://user-images.githubusercontent.com/66376344/201500893-d6a0b83a-9725-42eb-a58b-975941ea5dfa.png">

**Comment by frenck** [comment]
This is not something the add-on controls. The screenshot are from Home Assistant, not the add-on.

../Frenck

**Comment by nikogusm** [comment]
but i screenshotted it in the configuration panel of the spotify addon. are you sure?
