### ISSUE TITLE
Not able to start session

### ISSUE THREAD

**Issue by robinhood1596** [hassio-addons/addon-spotify-connect#200]
# Problem/Motivation

When using this add-on i can't simply start a new session in spotify. 

## Expected behavior

Calling the media_player.media_play function should start the music on spotify

## Actual behavior

It doesn't. Error log: No active playback device found. 

## Steps to reproduce

Restart everything, don't have music playing on any device and try to start. Not working.

## Proposed changes
If you start from other device and set source to home assistant and then close the other device it keeps working. Probably something to do with starting a new session/ keeping the player alive?

**Comment by frenck** [comment]
This is not an add-on issue, you are using the Home Assistant integration wrongly. Integrations are not related to add-ons.

../Frenck
