### ISSUE TITLE
allow to use additional librespot runtime options like initial-volume and volume-ctrl

### ISSUE THREAD

**Issue by mrvnklm** [hassio-addons/addon-spotify-connect#202]
# Problem/Motivation

> as my audio interface is always on high volume, because regulation is done via spotify, I would like to allow to set `--initial-volume` and `--volume-control` or maybe even more

## Expected behavior

> have an additional options field for advanced users

## Proposed changes

> if changes are welcome, I would write a pull request

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
I would also like to see a feature for setting the initial volume.  
Too often I wake everyone in the house and my neighbors 😁

This repo maybe has some useful information and hints on what to change.
It offers an default initial volume on add-on start. 
https://github.com/giannello/addon-spotify-connect  

Sadly the version currently provided doesn't work.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
i would still like to see this feature get implemented.

**Comment by mrvnklm** [comment]
@frenck What do you think?

**Comment by ElektronikCZ** [comment]
Hi, id also like to be able to control the volume. Spotify connect isnt very loud at full volume, about half as loud as my MPD player. There is no easy way to control pulseaudio volume directly, so i have to use the terminal to set the pulseaudio volume to 200%. Very annoying

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
bump

**Comment by escoand** [comment]
See https://github.com/hassio-addons/addon-spotify-connect/pull/103
