### ISSUE TITLE
WiFi speakers as HASS output

### ISSUE THREAD

**Issue by rwjack** [hassio-addons/addon-spotify-connect#204]
# Problem/Motivation
We're missing the ability to use HASS as the main spotify player, and have it stream output to other devices, such as connected wireless speakers (media_player/s)

## Proposed changes

addon audio configuration:
![image](https://user-images.githubusercontent.com/59068073/219752056-28b79e72-92cf-41dd-93cd-d4a832625d05.png)

random wifi speaker:
![image](https://user-images.githubusercontent.com/59068073/219752181-c80ac340-a06d-4c2a-b22f-bfc786c17ce8.png)

I'm unsure how feasible it would be to connect the Audio output of HASS in general, to connected wireless speakers.

**Comment by frenck** [comment]
That is a feature request for Home Assistant, not this add-on.

../Frenck
