### ISSUE TITLE
Source/device disappears after not using it for some time

### ISSUE THREAD

**Issue by T-vK** [hassio-addons/addon-spotify-connect#216]
# Problem/Motivation

It is not possible to select the HomeAssistant device as a source after not using it for a while (less than a day).

## Expected behavior

The HomeAssistant device source should always be available.

## Actual behavior

Spotify doesn't recognize the HomeAssistant device anymore after not using it for some time, meaning it can't be selected anymore. This means I have to restart the addon every time I want to use it...

## Steps to reproduce

Start the Spotify Addon, select HomeAssistant as the Spotify playback source. Stop playback, wait for a day. Now you won't be able to select and use the HomeAssistant source anymore.

## Proposed changes

Regularly send signs of life to the Spotify API, so it doesn't unlist the HomeAssistant device. Or maybe as a workaround for now: Regularly restart the addon or log out and in again automatically (unless of course it is currently being used).

Also see: https://github.com/librespot-org/librespot/issues/1102

**Comment by gbuktenica** [comment]
@T-vK, when this happens can you go to Settings > Addons > Spotify Connect > Configuration  
Under Audio > Output  
Is there anything selected or is it default?

**Comment by T-vK** [comment]
It's always set to Built-in Audio Stereo.
