### ISSUE TITLE
spotifyd crashed, halting add-on

### ISSUE THREAD

**Issue by ilsalgo** [hassio-addons/addon-spotify-connect#224]
I have a problem with the component, when I try to streaming on it my playlist, it crash: spotifyd crashed, halting add-o.
![IMG_0164](https://github.com/hassio-addons/addon-spotify-connect/assets/32997790/a8d41ce1-a77b-4540-a168-99de0eff55a5)

**Comment by Soteck** [comment]
Same here, after upgrading my home assistant for raspberry to Operating System 10.2

**Comment by shirou93** [comment]
Same here

**Comment by Gus1994** [comment]
Same here on rpi 3

**Comment by shirou93** [comment]
After update to newest version of supervisor spotify started work correctly.
