### ISSUE TITLE
Connect integration to add-on

### ISSUE THREAD

**Issue by Alwinator** [hassio-addons/addon-spotify-connect#237]
Unfortunately, the bot locked the PR thread, so I need to get in touch with you again here.

Based on your answer in my PR (_Originally posted by @frenck in https://github.com/hassio-addons/addon-spotify-connect/issues/235#issuecomment-1693735237_) I have started to develop an [HA integration](https://github.com/Alwinator/home-assistent-core/commit/8c97f2828b31da2a9db3f9df4c892562ec7c5a4f#diff-6a542280903daa2c35da57cd0f1807ac4cb57d8113cd4abc54e38d44eb591b49R14). This time it is the other way around: It is easy to emit events / create entities, but:

How can I get the logs from the Spotify Add-On from my integration? I need them to get the data. I thought of running bash commands and stealing the logs from docker, however, that seems to me more like a workaround.

What is the official way to solve my problem? I couldn't find anything on the web. If you could provide me a docs link, a code snippet, or a sample integration I would be very grateful.

**Comment by Alwinator** [comment]
@frenck :)

**Comment by Alwinator** [comment]
@frenck ;)

**Comment by Alwinator** [comment]
@frenck :)

**Comment by Alwinator** [comment]
Issue/Question still exists! :)

**Comment by frenck** [comment]
> How can I get the logs from the Spotify Add-On from my integration? 

You can't. Logs are not the responsibility of integrations.

../Frenck
