### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by pjangam** [hassio-addons/addon-spotify-connect#245]
# Problem/Motivation

>I installed add on was trying to configure spotify developer account etc. ddid not finish everything there.
After some time Addon was showing error so I uninstalled and tried to install back.
Error:
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 8:46:24 AM (8 occurrences) 
Last logged: 12:56:14 PM

Failed to to call /addons/a0d7b954_spotify/install - Can't install ghcr.io/hassio-addons/spotify/aarch64:0.12.6: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/spotify/aarch64:0.12.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
```

## Expected behavior

> Installation success
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> readlink /mnt/data/docker/overlay2: invalid argument

This is data corruption on your device / Docker end. This is not something the add-on can do anything about. Run `ha supervisor repair` to fix the issue and try again.

../Frenck
