### ISSUE TITLE
start fail

### ISSUE THREAD

**Issue by PINGWIXS** [hassio-addons/addon-spotify-connect#25]
after the big hass.io update the spotify add  on wont start

this is the log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
You are using a Raspberry Pi 1 or Zero.

See "Known issues and Limitations" section of the add-on docs.
