### ISSUE TITLE
Home Assistant Blue - No longer has the 3.5mm output option.

### ISSUE THREAD

**Issue by jplivingston08** [hassio-addons/addon-spotify-connect#251]
# Problem/Motivation

I use the Spotify connect to allow friends and family to stream to the speakers at our second home.  At some point during an update it stopped working.  I just now was able to review and see that the audio output option only allows for default and HDMI vs before it offered 3.5mm.  Hopefully this can be resolved.  

## Expected behavior

> Audio should play when you stream to it.

## Actual behavior

> Audio is playing but you cannot hear because it is sending out the HDMI port instead of the 3.5mm jack. 

## Steps to reproduce

> Install plugin on a home assistant blue.  Try to stream with an amp/speaker connected to the 3.5mm jack. 

## Proposed changes

> Add the hardware option back in.  this may be an issue with HA OS too. 
HA Core:
2023.11.2
HA Supervisor:
2023.11.3
OS: 
11.1

**Comment by iwannet** [comment]
I have the same issue

**Comment by tjorim** [comment]
This is out of control for this add-on. The options you see are provided by the supervisor.

**Comment by iwannet** [comment]
But how can i add the aux output then ?

**Comment by spudje** [comment]
Same here

**Comment by spudje** [comment]
> This is out of control for this add-on. The options you see are provided by the supervisor.

Supervisor or Hass OS? I created an issue at the Hass OS github https://github.com/home-assistant/operating-system/issues/3010

**Comment by frenck** [comment]
> This is out of control for this add-on. The options you see are provided by the supervisor.

Jorim is correct, this is not in control of the add-on itself. Please report the issue upstream in the Home Assistant project instead.

../Frenck
