### ISSUE TITLE
Spotify Connect device not showing as media_player device?

### ISSUE THREAD

**Issue by Anon666333** [hassio-addons/addon-spotify-connect#263]
Sorry if I'm misunderstanding anything here...this add-on works beautifully! My HA RPI is showing up in the Spotify app for all connected to the wifi, perfect!

However, I want this to also be usable with automations...this did not create an entity as I assumed it would for this device.
I called this "backyard speakers" and I assumed an entity would be created called "media_player.backyard_speakers", but that doesn't seem to be the case.
Am I missing something? 

* edit *
To clarify what I'm looking to do, I'd like to group my google nest speaker and this spotify connect device (my HA server) as one group speaker that I can then play music from so I'll have music inside and outside.

**Comment by ArthFink** [comment]
I'm looking for a similar functionality


As well as the option of using cast devices as an output, but this might be a different topic in it self

**Comment by Anon666333** [comment]
> I'm looking for a similar functionality
> 
> 
> As well as the option of using cast devices as an output, but this might be a different topic in it self  

So let me tell you my "solution".

I installed the VLC Media Player add-on, this turned my pi into a media player.
Problem was, I couldn't play spotify on it and I still wanted it synced with my nest speakers.

To resolve this, I used Music Assistant. It allowed me to create a "group" of speakers, with their own new entities, that can be used for automations!

The nest speakers and backyard speakers are not perfectly synced, but it works.

Not sure if this answers your question or not, but I was able to get to a fairly workable solution this way, hoping it does the same for you!

**Comment by ArthFink** [comment]
@Anon666333 how did you configure your VLC? I had attempted this as well, but I had no luck. But this also might be because I'm using a Bluetooth connection to the speaker, and VLC can't handle that.

**Comment by Anon666333** [comment]
> @Anon666333 how did you configure your VLC? I had attempted this as well, but I had no luck. But this also might be because I'm using a Bluetooth connection to the speaker, and VLC can't handle that.

What is your bluetooth speaker connected to? Your HA Server? 
I believe the VLC Add-On allows you to now see your HA Server as a media_player device, which you can then choose the default audio output channel, in my case it was the speaker jack on my Pi, but you may be able to define the bluetooth channel, but it will most likely require further configuration, if it's even possible.

I wouldn't recommend bluetooth personally, as it's likely to disconnect at some point. If you can hard-wire, that's always my recommendation.

To configure the VLC I just added the Add-On from the Add-On store, no real configuration needed. Once it was added the entity appeared and I renamed it as needed.

I confirmed it worked by testing some kind of audio through VLC directly, and after that, used Music Assistant to then control any audio playback. It created it's own entity as well so I don't really use the VLC entity, it was more of a means to an end to get MA doing what I needed.

I'm happy to help if I can, show me what you're working with.

**Comment by frenck** [comment]
> Spotify Connect device not showing as media_player device?

This is an add-on not an integration. There is no integration or entities involved here.

I think you are mixing up concepts.

../Frenck

**Comment by Anon666333** [comment]
> > Spotify Connect device not showing as media_player device?
> 
> This is an add-on not an integration. There is no integration or entities involved here.
> 
> I think you are mixing up concepts.
> 
> ../Frenck

Absolutely correct, my apologies for misguiding!

@ArthFink, once you install the Add-On and have it running, you must then add the _integration_ which is going to then create the entity for your devices, which can then be used with the Music Assistant Add-On & subsequent Music Assistant Integration.
