### ISSUE TITLE
Music is playing entity

### ISSUE THREAD

**Issue by Brachyurus** [hassio-addons/addon-spotify-connect#278]
### Discussed in https://github.com/hassio-addons/addon-spotify-connect/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **JeroenV99** August 12, 2024</sup>
I’m interested in adding a feature to the Spotify Connect integration that would provide an entity or attribute to indicate whether music is currently playing. This would help in automating the connection to a Bluetooth speaker when playback starts.</div>

**Comment by tjorim** [comment]
This add-on will not provide entities to Home Assistant. Add-ons just run the program in a separate Docker container. If you want something in Home Assistant, you'll need a home assistant (custom) integration.
