### ISSUE TITLE
Prevent a CEC-enabled TV from coming out of standby

### ISSUE THREAD

**Issue by jvravensberg** [hassio-addons/addon-spotify-connect#3]
# Problem/Motivation

First of all, great add-on to Home Assistant! Thanks for bringing this to Hass.io! I'm slowly migrating from Raspbian to the Hass.io platform and I'm now switching from Raspotify to this new add-on. I installed the add-on and plugged it into my receiver. As the Raspberry Pi 3 Model B+ is sending a CEC signal on boot, my TV and receiver will both turn on after a reboot of the Raspberry Pi. This also switches the TV channel to the Raspberry Pi input, which is annoying as I'm only using the Pi for music and Home Assistant.

## Expected behavior

The TV should not turn on by CEC.

## Actual behavior

The TV turned on and switched channel to the Raspberry Pi.

## Steps to reproduce

Connect the Raspberry Pi with the latest Hass.io and Spotify module to a CEC-enabled TV. Restart the Raspberry Pi. It should turn on the TV and switch channels to the Raspberry Pi.

## Proposed changes

With Home Assistant running on Raspbian, I used `hdmi_ignore_cec_init=1` in the boot/config.txt to get this fixed. I don't see a possibility to do this now with Hass.io. ([More info](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md))

As some users might also use plug-ins that requires CEC, it should be an easy to enable/disable setting in the plug-in or in Home Assistant.

Thanks!

**Comment by frenck** [comment]
The solution relies upon chancing HassOS (source) or the HassOS config. This is not something the add-on can provide.

The boot config is still available on HassOS, so you can create the same change.

**Comment by jvravensberg** [comment]
Thanks @frenck for pointing me into the right direction. Googling for HassOS instead of Hass.io learned me that the boot config is located in a FAT-partition on the SD-card. To fix this issue, connect the Micro-SD card to a (Windows) computer, open the boot config file which is in the root of the partition and specify `hdmi_ignore_cec_init=1`. Put the Micro-SD card back into the Raspberry Pi and it's fixed!
