### ISSUE TITLE
Requires restart every time I use it

### ISSUE THREAD

**Issue by leona** [hassio-addons/addon-spotify-connect#30]
# Problem/Motivation

Every day I need to restart the addon in hassio for it to show up in spotify. The green icon indicating it is running is on but the log doesn't show anything until I restart. I've had this add-on for a long time and have always updated it but nothing has changed. It's not the worst thing, I really like this add-on, but it would be great if I didn't have to go through the hassio panel every time I want to use it. Has anyone else encountered this?

**Comment by dannyshaw** [comment]
I have the same problem. Any time I open spotify to send it to this target it's missing and I need to restart it. "Start on boot" is also selected and it doesn't start on restarting hass either.

**Comment by parhedberg** [comment]
I also had this issue in the closed ticket "https://github.com/hassio-addons/addon-spotify-connect/issues/27"

The problem is not resolved, but it it better now when i added the automation suggested in the other ticket..

**Comment by yevon** [comment]
I'm having this issue also, it hangs time to time and I can't see the device to play music on it. With a simple restart gets fixed. It might be a good idea to implement some keep alive to get sure spotify server keeps the device alive.

**Comment by Tafelbomber** [comment]
Exact same problem for me. Restarting the addon manually always fixes the problem and it shows up in all my Spotify instances within seconds, though.

**Comment by seife96** [comment]
Same Problem for me. Every time I want to use it i have to restart it

**Comment by leikoilja** [comment]
Same same

**Comment by Naish73** [comment]
Same issue here. I need to restart to show up hass.io again.

**Comment by heikotroetsch** [comment]
Nope, not stale, still a problem.
