### ISSUE TITLE
Not showing in other Spotify accounts on same wifi?

### ISSUE THREAD

**Issue by parhedberg** [hassio-addons/addon-spotify-connect#31]
# Problem/Motivation

My girlfriends Iphone has never seen the hass.io spotify speakers, and can not use them, but i can with my android..

## Expected behavior

I am guessing that this is due to that we are logged in to different accounts? But i thought that she would see the speakers and use my account to play music?

## Actual behavior

She can't se the speakeras

## Steps to reproduce

Share a speaker in hass.io with one account. Try to see it (using the same wifi) on a phone with spotify logged in with a different account..

## Proposed changes

Is it possible to use multiple accounts in configuration?

**Comment by frenck** [comment]
That is correct behavior, it is Spotify connect, it is connected to an account and is solely available in that account.
