### ISSUE TITLE
Pick other Spotify Connect devices

### ISSUE THREAD

**Issue by iAbadia** [hassio-addons/addon-spotify-connect#32]
# Motivation

> As I see this addon only allows to use your Hass.io instance as a Spotify Connect device. It'd be very useful for it to also add a UI card and/or expose a service to pick another Spotify Connect device from the available list.

> My use case for this: I have a Yamaha AV receiver that is Spotify Connect capable, I can select it manually from the Spotify app but I would love to be able to tell my Google Home to play something on Spotify on that device (which I can't because it's not a chromecast). If this addon allowed me to pick a device I could expose a switch to Google Home that when flipped would call a service to select the Yamaha AV as the current Spotify Connect device.

**Comment by frenck** [comment]
You are confusing add-ons & Home Assistant integrations now.
The add-on does not provide cards or services, those are provided by integrations.
