### ISSUE TITLE
Launch spotifyd in discovery mode

### ISSUE THREAD

**Issue by makruiten** [hassio-addons/addon-spotify-connect#33]
# Problem/Motivation

Spotify Connect is invisible to other accounts on the same network. [Librespot](https://github.com/librespot-org/librespot) doesn't have this limitation and from what I gather [spotifyd](https://github.com/Spotifyd/spotifyd) can also be launched in discovery mode when the username and password are left empty. They do mention that there is a [known issue](https://github.com/Spotifyd/spotifyd/issues/373) with that, but I'm not sure what's the current status.

## Expected behavior

Spotify Connect is discoverable on the network.

## Actual behavior

Spotify Connect is linked to a specific account.

## Steps to reproduce

By design, so no steps to reproduce.

## Proposed changes

I propose that your add-on should allow launching spotifyd in discovery mode by not providing a username and password. If it doesn't work users can always just launch it with a username and password like before.

You might have already tried this, but I could only find issues saying that this is not (yet) possible with the spotifyd backend.

**Comment by makruiten** [comment]
I should add that discovery mode is actually working for me with librespot on raspbian and on kodi, so I know that it's not only technically possible, but it also works in practice.

**Comment by toMeloos** [comment]
+1 for this feature request. This makes total sense in a home where family members could have multiple accounts and when you have guests over that would also want to be able to play something on the stereo system using spotify.

**Comment by shirou93** [comment]
I'm waiting :)

**Comment by sinclairpaul** [comment]
You may want to stop waiting and look at the release notes for 0.7.0... 😉

**Comment by shirou93** [comment]
When i leave empty username addon don't start.

**Comment by sinclairpaul** [comment]
Post your log and config in a new issue.
