### ISSUE TITLE
BadCredential error if # in password

### ISSUE THREAD

**Issue by MLaudren** [hassio-addons/addon-spotify-connect#35]
# Problem/Motivation

If the password have a # in it, the authentication fail with a BadCredential error.

Probably link to the fact that # is use for comment in bash and some other programming language.

## Expected behavior

Password with # character should be accepted.

## Actual behavior

Having a # in the password give a BadCredential error.

## Steps to reproduce

add a # at any position in the password to reproduce the behavior

## Proposed changes

Issue with escaping character?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by MLaudren** [comment]
I think the issue come for spotifyd.sh, but not sure how to fix it.

**Comment by frenck** [comment]
We can't fix it right now, since the upstream has the issue as well.

It will be fixed, once the upstream project we use fixes it as well.

Closing for now.
