### ISSUE TITLE
hassio entity not appearing, add-in running well

### ISSUE THREAD

**Issue by markdswan926** [hassio-addons/addon-spotify-connect#36]
Hi,

Fairly new to hassio in general, so I'm very aware this may be me being newbie.

I have installed the Spotify connect add-in in hass.io, configured the config file and started, the log looks happy (even at debug level), but I cannot seem to add the entity in dashboard etc.

Any thoughts?

Thanks in advance

**Comment by tjorim** [comment]
> but I cannot seem to add the entity in dashboard etc.

Which entity in which dashboard?

**Comment by markdswan926** [comment]
When I try and add the spotify add-in to the hassio overview its doesn't appear as an available entity

**Comment by frenck** [comment]
Add-ons do not provide entities. Add-ons provide services.
Home Assistant integrations provide entities.
