### ISSUE TITLE
rPI4 sound only over HDMI

### ISSUE THREAD

**Issue by MLaudren** [hassio-addons/addon-spotify-connect#37]
# Problem/Motivation

Using a rPI 4, When playing sound from spotify, the jack keep silent.
If plugin a hdmi on hdmi0 port and turning on the TV, the sound is played on the TV.

I did try with the 3 available output shown in the addon page, but the result is always the same.

## Expected behavior

Being able to play sound using the jack.

## Actual behavior

Sound played only through hdmi

## Steps to reproduce

add the 'spotify connect' addon,
provide your credential for the service to login
select any of the 3 output
Plug a hdmi cable (if not plug qnd play, rPI need to be restarted with the cable plugged)
turn the TV on
select the home-assistant playback device in spotify
play sound on spotify

> Music come from the TV

## Proposed changes

None

**Comment by grunjol** [comment]
I had the same problem with a rPi3. Ended up using an automation to initialize the alsa mixer correctly.

To verify if is the same problem.

Run this command in homeassistant container

`amixer cset numid=3 1`

if amixer is not installed run

`apk add alsa-utils`

I

**Comment by grunjol** [comment]
I created a gist with the package I use, (based on other people comments and snippets)

**Comment by MLaudren** [comment]
I tried your command but I'm not able to have any result:

If I execute the command `$ amixer cset numid=3 1`
I have the following error:`amixer : Control default open error : no such file or directory`

If I put a usb card, I'm able to have sound from it if I choose it in the plugin.

**Comment by grunjol** [comment]
I dont know which device is using by default so, try
 `amixer -c 0 cset numid=3 1`
or
 `amixer -c 1 cset numid=3 1`

**Comment by frenck** [comment]
Unfortunately, this cannot be fixed at the add-on side of things.

A change in the Home Assistant Supervisor is on route to take care of that in the near future.
