### ISSUE TITLE
Request: have spotify player as a device or entity in HA

### ISSUE THREAD

**Issue by jzee** [hassio-addons/addon-spotify-connect#38]
# Problem/Motivation

The add-on works great! Thanks for making it and investing the time to make it work so flawlessly. 

As a feature request, I'd like to trigger an automation based on the play/pause state and am hence looking to have it exposed in HA: My HA is connected to a classic amp + loudspeaker pair and I'd like to turn on the amp using a remote-controlled wall-socket as soon as the player comes on. Whenever it's done playing for a minute or two, I want to turn the amp off again. 

## Expected behavior

Have the spotify player appears as a (restricted) media_player in HA. If that's not possible, at least expose its state or play events so automations can be triggered based on it.

## Actual behavior

The spotify player works fine but does not expose its state to the HA instance it runs on

## Steps to reproduce

Start the add-on, notice it doesn't appear in Entities, Devices or Integrations

## Proposed changes

Wire the controls of a media_player to the add-on so it's fully integrated into HA. Alternatively, offer events that indicate what happened, allowing a reaction inside HA.

**Comment by frenck** [comment]
Add-ons have no influence on the integration in Home Assistant.
Furthermore, add-ons wrap existing applications, we cannot modify the application itself.
