### ISSUE TITLE
Discovery Mode needs access to local network

### ISSUE THREAD

**Issue by grunjol** [hassio-addons/addon-spotify-connect#39]
# Problem/Motivation
Recently discovery mode was added but it doesn't seem to work https://github.com/hassio-addons/addon-spotify-connect/issues/33#issuecomment-576923911

## Expected behavior

If you leave username and password empty, a spotify connect instance should be discoverable on the local network instead of establish a connection with spotify api.

## Actual behavior

The instance is not discoverable on the local network BUT appears on the bridged (private) hassio network (i can see the HA discovers the instance but its an unknown type, so it discards it)

## Steps to reproduce

Run addon in discovery mode (empty user/pass)

## Proposed changes

librespot uses mDNS to publish the listening port. mDNS uses IP multicast but is bounded to the internal private network, so it doesn't propagate to the users/clients .

A possible solution could be set host_network: true in the addon config

**Comment by grunjol** [comment]
I cloned the repo and added "host_network": true in the config file and can confirm discovery is working fine in local network

**Comment by daerSeebaer** [comment]
@grunjol where exactly did you add that line? do you want to make it a pull request?

**Comment by grunjol** [comment]
I think frenck just did it here https://github.com/hassio-addons/addon-spotify-connect/commit/28d11d8c2d36cf689f7a0642aa93e5315089afc3

**Comment by frenck** [comment]
Yes, but we are not there yet...  Home Assistant gets a new audio layer, which we are currently testing with this add-on as well.

**Comment by frenck** [comment]
v0.8.0 released.
