### ISSUE TITLE
how do I use it without a .io install? im running my hass on VM

### ISSUE THREAD

**Issue by darkgeej** [hassio-addons/addon-spotify-connect#4]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You can't. Add-ons is a feature only available on Hass.io.
