### ISSUE TITLE
Bluealsa output

### ISSUE THREAD

**Issue by cerberek** [hassio-addons/addon-spotify-connect#40]
# Problem/Motivation

I have bluetooth speaker connected to my Rasberry through bluealsa. And I'm searching for way how to add bluealsa output to this plugin. Maybe you can advice?
> (Why the issue was filed)
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You can't at this point. This is not an add-on limitation.
However, work on improving the audio layer of Home Assistant is in progress.
