### ISSUE TITLE
Alsa output disappear on output

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-spotify-connect#41]
# Problem/Motivation

No alsa in rpi3 b+ to choise only "Built-in Audio Digital Stereo (IEC958)",
 
Glitch sound freezing

## Expected behavior

 Choise alsa sound and normal music on 3.5 mm jack

## Actual behavior

I'ts working normalny yesterday. Today my output disappear. (Raspbian buster)
![Screenshot_20200304-014031](https://user-images.githubusercontent.com/59237288/75833678-0c4e9c00-5dba-11ea-860c-70ffe9f21448.jpg)

**Comment by frenck** [comment]
This interface is not provided by the add-on but by Home Assistant.
The add-on cannot fix or improve this, cause it is not our code.

Please report your issue at Home Assistant (Supervisor).

Thanks 👍
