### ISSUE TITLE
Sound distortion on RPi4

### ISSUE THREAD

**Issue by Maco65** [hassio-addons/addon-spotify-connect#42]
# Problem/Motivation
Spotify add-on not possible to use - music played with "terrible" distrotion.

> (Why the issue was filed)

## Expected behavior
Normal music played

> (What you expected to happen)

## Actual behavior
And afternoon tried to use Spotify plugin - possible to connect from laptop but no music. I have uninstalled and installed again and this made music played but with strange distortion - actullay not possible to listen.

> (What actually happened)
2 days ago I have upgraded to version 0.8.0 and new functionality (disocvery) was working great and music was playing with no problems.
Yesterdau I have upgarded hass.io core to 0.106.4 and today to 0.106.5. - maybe this is the problem ?
When I check the hardware from Supervisor/SYSTEM/HARDWARE option i see the following on audio:
audio:

    0:
        name: bcm2835_alsa - bcm2835 ALSA
        type: ALSA
        devices:
            [object Object]
            [object Object]
            [object Object]

I think some time ago I coudl see some devices...

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Maco65** [comment]
I am sorry if I have not provided enough data. I am new to GitHub and also fresh on Home Assistant (started for the first time 3 weeks ago). Running on RPi4 2GB installed from image "Raspberry Pi 4 Model B 32bit (recommended)"

**Comment by frenck** [comment]
This is probably caused by the upgrade of the Supervisor, which contains a new audio layer. As you stated, it worked fine until your upgraded another part of your system.

Please report the issue @ Home Assistant (Supervisor repository). Thanks.

**Comment by Maco65** [comment]
Thank you.
If new upgarde contains new audio layer - shoudl this add-on be able to use it ?
I am afraid that when I report the issue to Home Assistant and report that my Spotify Add-on is not working they will send me to add-on author claiming that there is no other issue on HA ?

**Comment by frenck** [comment]
Yes, the add-on has been part of the test for the new audio layer.
I'm quite sure your issue will be OK to report over there, as I work for Home Assistant as well 😉
