### ISSUE TITLE
Slow song

### ISSUE THREAD

**Issue by WAPEETY** [hassio-addons/addon-spotify-connect#43]
I don't know why but if I try to put a song it seems that is going too slow, I have Spotify premium

**Comment by arexam** [comment]
I've got the same problem since yesterday. Every song sounds like stuck vinyl record. 😣
Addon version 0.80, home assistant 0.106.5 system 3.12.

**Comment by frenck** [comment]
This is not an add-on problem, but an issue with Home Assistant. Please open an issue there.
