### ISSUE TITLE
Not possible to select the device from other Spotify instances

### ISSUE THREAD

**Issue by Maco65** [hassio-addons/addon-spotify-connect#44]
# Problem/Motivation
I hope this issue is not related to this one: https://github.com/home-assistant/audio/issues/7#issuecomment-596458346
From my prospective after upgrading to "HassOS Release-3 build 12 (Stable)" I am not able to select this add-in device from other instance (like spotify app on my phone).
> (Why the issue was filed)

## Expected behavior
I should be able to select "HomeAssistant" (default device name in configuration file of the add-on) from any my other Spotify app running on the same network.
> (What you expected to happen)

## Actual behavior
Now I can see this device but it is "gray" and not possible to select it, see picture below:
![obraz](https://user-images.githubusercontent.com/18126641/76235714-c9fae400-622b-11ea-9ba3-8c78d2e6dae7.png)

> (What actually happened)
I have uninstalled and installed add-one, restarted hassio, restarted laptop. No change.
Here is the log from add-on:
``` -----------------------------------------------------------
 Hass.io Add-on: Spotify Connect
 Play Spotify music on your Home Assistant device
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 209
-----------------------------------------------------------
```
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I'm sorry, but yes, it is related to the issue linked.

**Comment by Maco65** [comment]
OK. Thanks. :)
