### ISSUE TITLE
Noisy sound  output on Raspi3 after Hassos , HA update ( same addon version 0.80)

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-spotify-connect#45]
# Problem/Motivation
distorted audio on Rpi after Hassos update
> (Why the issue was filed)

## Expected behavior
the addon was working perfect prior to hassos 3.12 ,  unsure what is generating the incompatibility 
> (What you expected to happen)

## Actual behavior
the audio is totally distorted like being received at a very low  bpm rate .
> (What actually happened)

## Steps to reproduce
just use a PI3 , with hassos 3.12 and HA 106.5
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
#42 #43
