### ISSUE TITLE
RPI4 volume issue

### ISSUE THREAD

**Issue by Karel-de-Kleine** [hassio-addons/addon-spotify-connect#46]
# Problem/Motivation

When streaming with my RPI4 the audio on full volume, the sound is just full off noice. Like the speakers can't handle the audio.

## Proposed changes

By setting the volume of spotify to 25% the audio is fine. Any louder through the app and the music quality is terrible.

**Comment by frenck** [comment]
This add-on does not manage volume levels of your audio device.

**Comment by Karel-de-Kleine** [comment]
I thought so. Strange, because when on higher than 25% of the spotify volume, the audio sounds like if you're exploding your speakers. but the speakers volume is at low. Plugging it in with my phone it can get much louder.
