### ISSUE TITLE
Feature Request - Enable Pipe Audio Output 

### ISSUE THREAD

**Issue by almostserious** [hassio-addons/addon-spotify-connect#48]
Would it be possible to add the option to play the audio to a named FIFO pipe?
According to the spotifyd issue #198 (https://github.com/Spotifyd/spotifyd/issues/198) this can be achieved by changing the spotifyd.service file and and append to the ExecStart line.

With a named pipe the playing audio could be used in conjunction with a multiroom player like snapcast server, pushing the Spotify Audio into all the rooms in sync.

**Comment by frenck** [comment]
No that is not possible.
