### ISSUE TITLE
Add Dac support

### ISSUE THREAD

**Issue by mullermeck** [hassio-addons/addon-spotify-connect#49]
# Problem/Motivation

Able to use dac to improve sound quality. The pie audio jack is famous for bad audio quality,

## Proposed changes

Able to use a different type of hats and generic soundcard via io pins. Probably a config for change different amps.

**Comment by frenck** [comment]
Sorry, audio devices are not implemented by the add-on by supplied by the system.

**Comment by mullermeck** [comment]
Okej, thanks for the fast answer. How is the BT audio quality of the PI?

**Comment by mullermeck** [comment]
Ok, but thanks for the fast answer!
