### ISSUE TITLE
ChannelError. Next song not loaded.

### ISSUE THREAD

**Issue by kcvanderlinden** [hassio-addons/addon-spotify-connect#50]
So I was listening to spotify via my Hassio installed on Docker through a USB DAC without problems for a long while, but suddenly it stopped. The next song could not be loaded. In the add-on log for Spotify Connect the following error appeared every time i tried to load a song. The issue had resolved itself after some time, because when I tried to load a song after dinner, it played my requested songs without problems.

Anyone a clue how this issue can be resolved?

I inserted {my-own-username} for the sake of privacy.

```
[19:17:55] INFO: Starting the Spotify daemon...
Loading config from "/etc/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "gew1-accesspoint-b-7q0z.ap.spotify.com:443"
Authenticated as "{my-own-username}" !
Using alsa sink
Country: "NL"
Loading <Home> with Spotify URI <spotify:track:0ZUMBOzlwNXfVE4Z8lSrsd>
channel error: 2 1
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
Player thread panicked!
```

This is my configuration of the add-on:
```
name: ZwoelStation
bitrate: 320
```

**Comment by shirou93** [comment]
I have same issue.

**Comment by martinschilliger** [comment]
It looks like a problem from spotifyd:
https://github.com/Spotifyd/spotifyd/issues/131
https://github.com/Spotifyd/spotifyd/issues/657

**Comment by davidrustingha** [comment]
```
channel error: 2 0
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
Player thread panicked!
```
Same here, also with bitrate 160 @martinschilliger

**Comment by martinschilliger** [comment]
Ok, I think we cannot do anything than wait for librespot to fix it. As I understand it's something related to the encoding of the songs.
