### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by Tokn59** [hassio-addons/addon-spotify-connect#51]
Hi, Thanks for sharing this with the community !

I tried to configure the Spotify Connect in Home Assistant (latest build) according to the documentation. This is my config : (exact user data changed for security reasons)

name: HomeAssistant
bitrate: 160
username: 123457890
password: mysecretpassword

When I press save I get the following error message : 

**Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'name': 'HomeAssistant', 'bitrate': 160, 'username': 123457890, 'password': 'mysecretpassword'}**

Any idea what I do wrong here ?

Thanks & kind regards,

Tony

**Comment by Tokn59** [comment]
Ok ... Got it to work at least as far as the configuration is concerned ... You need to fill in your email address in username and nit your (numeric) Spotify user name.

**Comment by frenck** [comment]
Correct, it is either your username (for older accounts) or your email.
The account ID is not used.
