### ISSUE TITLE
Add configuration option for linear volume

### ISSUE THREAD

**Issue by giannello** [hassio-addons/addon-spotify-connect#54]
# Problem/Motivation

`librespot` supports a `--linear-volume` option that allows a - subjectively - better user experience. The default volume scale is precise at low volumes, and blows up speakers as soon as the dial is turned past a certain point, and the problem gets worse with more powerful DACs/amps.

## Expected behavior

Allow using `linear-volume` as a configuration parameter

**Comment by frenck** [comment]
This tool does not run librespot...
