### ISSUE TITLE
The add-on tries to read packets from shelly devices

### ISSUE THREAD

**Issue by WAPEETY** [hassio-addons/addon-spotify-connect#55]
I updated the system to 0.115.3 and now  I'm not able to see the device in Spotify, searching in logs I found this:

```
couldn't parse packet from V4(192.168.1.4:5353): type 47 is invalid

```

In my network on that address there's a Shelly with original firmware, as MQTT broker I use on my raspberry Mosquitto broker

**Comment by jleitaopt** [comment]
I have the exact same log messages. It doesn't appear to affect anything. It just fills the log...

**Comment by WAPEETY** [comment]
Ok but my problem (I can't see the device in Spotify) still remains

**Comment by frenck** [comment]
It received an invalid broadcast packet from an upstream device. The add-on cannot do much about that. The issue is the device that sends those invalid packets. Please report your issue with the manufacturer of that device.

**Comment by dtx360** [comment]
Add-on works as expected, still these log entries are filling up the log. Setting the log level to fatal does not stop the output. So if I understand Frenck correctly, these messages cannot be prevented to write to the log file?
