### ISSUE TITLE
password doesn't allow just numbers

### ISSUE THREAD

**Issue by uferes** [hassio-addons/addon-spotify-connect#57]
`Configuration

name: HomeAssistant
bitrate: 320
username: ha+ha@gmail.com
password: 00000666`
​
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'name': 'HomeAssistant', 'bitrate': 320, 'username': 'ha+ha@gmail.com', 'password': 00000666}

**Comment by frenck** [comment]
It expects a string, in YAML you'll need to enquote it.

e.g.:

```yaml
password: "0000000555"
```
