### ISSUE TITLE
Next song ‘event’

### ISSUE THREAD

**Issue by davidrustingha** [hassio-addons/addon-spotify-connect#58]
Would it be possible to have events for the next song. In the log of the integration you see which song is currently playing and which songs have been played already. 

I would love it if I could create automations based on that data!

**Comment by frenck** [comment]
Assuming you are talking about Home Assistant events here. This is not part of the add-on, nor the responsibility of an add-on.

If you are interested in automating Spotify with Home Assistant, please take a look at the Spotify integration for Home Assistant.

**Comment by davidrustingha** [comment]
Hi Frenck. I am indeed talking about Home Assistant events. 
I am already automatisch the Spotify Addon, but when a guest plays music I have no media_players that update since his account isn’t integrated. The only reference I have is the Spotify Connect add on log.

Would it be possible for an add on to send out events?

**Comment by frenck** [comment]
See my previous answer

**Comment by pax0r** [comment]
@davidrustingha If you still need this I have forked this addon and implemented simple events: https://github.com/pax0r/addon-spotify-connect
It uses `on_song_change_hook` from spotifyd, but it will not send song names only IDs. 

I wanted to automated changing audio source on my sound system to the input connected to the Home Assistant when playing music using this add-on. Spotify Integration was not an option as reaction was to slow for this use case (few seconds at least before changing state). With events directly from the addon works like a charm!

@frenck if you would change your mind about events sends by this add-on I can prepare PR with this change.
