### ISSUE TITLE
Addon stoped working after OS 5.8 update ?

### ISSUE THREAD

**Issue by Maco65** [hassio-addons/addon-spotify-connect#61]
# Problem/Motivation

Add-on stopped playing at all. It might be related to the fact that today I have upgraded OS to 5.8 and Supervisor to 2020.12.1

## Expected behavior

Play music once the RPi device is selected from Spotify app

## Actual behavior

Nothing happens - no error, no message, no music (which for sure is played when selecting computer)

## Steps to reproduce

I have removed add-on and installed again. The same issue.
Add-on config:
```
name: wzmacniacz
bitrate: 160
```

There are errors in log:
```
ALSA lib pcm_pulse.c:752:(pulse_prepare) PulseAudio: Unable to create stream: No such entity
Alsa error PCM open ALSA function 'snd_pcm_hw_params' failed with error 'EIO: I/O error'
Could not start audio: Alsa error: PCM open failed
```

Have tried to select different output (I have also USB sound card connected to RPi) and it works fine. The above error in log is only when I select `Default` Output.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by zepfietje** [comment]
I'm also running into this issue (same errors in my log).

**Comment by Maco65** [comment]
There seem to be workaround for me to select in Add-on configuration tab specific Audio output ( in my case it is **Bulit-in Audio Stereo**) with such selection music is played normally and logs are correctly showing what is played. As soon as I select "Deafult" then there is no sound and errors in the logs.

**Comment by zepfietje** [comment]
Thanks @Maco65, works for me too!

**Comment by zaggash** [comment]
I had the same issue.
When I select the device name in Spotify, it didn't play any sound.
Then I change the default output but the sound quality is really bad, like a weird sound with a lot of distortion.
I switched to this addon https://github.com/giannello/addon-spotify-connect-librespot and it is working.

**Comment by Maco65** [comment]
@zaggash thanks. How do you install this addon ?

**Comment by zaggash** [comment]
Please find the information below on how to setup the other addon @Maco65 
https://community.home-assistant.io/t/home-assistant-community-add-on-spotify-connect/61210/137

**Comment by Maco65** [comment]
In my case the issue is still open and to be honest the problem is not always the same... :(
Now, when I test the issue is that whenever I use "Default" in Add-on Configuration Audio Output there is no sound at all.
When I select "Bulit-in Audion Stereo" or another USB Sound card I have (connected to RPi) the sound is OK.
So, selecting Default does not work at all and previous;u has generated serious distortion.
I am on latest versions of Core (2021.2.3), Supervisor (2021.02.11), OS (5.11) and Spotify Add-on (0.8.2).

**Comment by Maco65** [comment]
Well... since there is no news that anything was changed I do not see the reason/motivation to test again :(
I have switched to another Spotify Add-on and I do not use this one.
If anybody will ask me to do something to diagnose the issue I will be happy to to this.
Such repeating message from bot does not change the case I think.

**Comment by Maco65** [comment]
I gave up. I stop using this Add-on, so I do not know if the issue is fixed or not. I am using another plugin which is working with no problems for several weeks now.

**Comment by Drachenfalke12** [comment]
Hey @Maco65,
which plugin are you using instead? I need an alternative too ig

**Comment by Maco65** [comment]
> 
> 
> Hey @Maco65,
> which plugin are you using instead? I need an alternative too ig

https://github.com/giannello/addon-spotify-connect-librespot
