### ISSUE TITLE
Add option for piped output for snapcast/forked-daapd

### ISSUE THREAD

**Issue by tillmannschatz** [hassio-addons/addon-spotify-connect#62]
# Motivation

Enable usage of Snapcast or Forked-daapd

## Expected behavior

enable to pipe the output to snapcast/forked-daapd 

## Proposed changes

See Ulrar's repository: [link](https://github.com/Ulrar/hassio-addons)
with options:
`backend: pipe`
`device: /share/forked-daapd/music/YOURPIPE`

**Comment by frenck** [comment]
Nope. This add-on does not manage audio devices.
