### ISSUE TITLE
Spotify stops playing randomly, "Connection reset by peer"

### ISSUE THREAD

**Issue by tbhsm** [hassio-addons/addon-spotify-connect#63]
# Problem/Motivation

The problem started to occur after upgrading from 2020.12.1 to 2020.12.2. I tried reverting using a snapshot (just reverted HA) but it is still happening, it is barely usable at the moment :(

## Expected behavior

Continuous playing of songs.

## Actual behavior

Randomly stops music several times a day. Details in logs:

> Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

## Steps to reproduce

Play music and wait for it to happen.

**Comment by frenck** [comment]
> Connection reset by peer

Mean the remote connection dropped. There is not much I can do about that from an add-on perspective.

**Comment by tbhsm** [comment]
It doesn't recover though, and drops from the list of Spotify Connect devices. The only way I can resume playing music it is by rebooting it in my HA installation, which is quite annoying.

**Comment by frenck** [comment]
Add-ons are not related to the HA installation itself, so rebooting doesn't make much sense as a resolvement (or at least, a bit of a hard measurement).

**Comment by tbhsm** [comment]
That makes sense. However, whatever is causing this in my HA installation is causing my Spotify to become permanently unavailable until rebooting (just the add-on). Doesn't that mean the add-on is unable to deal with such errors?

**Comment by tbhsm** [comment]
Found a workaround in #24 that automatically resets Spotify Connect when it dies. Still stops music, but saves me the hassle to reset the add-on..

**Comment by Beater-Garage** [comment]
I'm seeing the same issue, resetting the add-on allows the device to become discoverable again. This is quite interruptive but the #24 method should make it less of a hassle.  Perhaps a wired connection would prove more reliable.

**Comment by tbhsm** [comment]
> I'm seeing the same issue, resetting the add-on allows the device to become discoverable again. This is quite interruptive but the #24 method should make it less of a hassle. Perhaps a wired connection would prove more reliable.

My connection is wired in fact, and quite stable over the day. From the automation, I noticed it takes exactly 2 hours after pressing play until Spotify gets reset.

I'll be using the motto "it's not a bug, it's a feature". The feature being an auto-stop feature in case I forget to turn it off :p
