### ISSUE TITLE
Spotify connect addon is not visible on my devices list.

### ISSUE THREAD

**Issue by zaggash** [hassio-addons/addon-spotify-connect#64]
# Problem/Motivation

I cannot see the device in my Spotify connect devices list.

## Expected behavior

I should see it along with my others devices

## Actual behavior

I just see my Spotify connect DENON device ( Home Cinema amplifier ) and my Browser when I open Spotify on it.
I cannot see the add-on device.

## Steps to reproduce

My current network setup is the following.
I have a modem linked to my router/firewall.
Then my firewall has a dedicated link for my LAN that goes to a switch.
On my switch, I have an Unifi AP for Wi-Fi devices where HomeAssistant is plugged.

Doing a few research, I figured during a Wireshark scan that the TTL for the mDNS answer of the addon is only 1.
So the packet is lost before it reaches the destination.
```
Time to Live: 1
    [Expert Info (Note/Sequence): "Time To Live" != 255 for a packet sent to the Local Network Control Block (see RFC 3171)]
        ["Time To Live" != 255 for a packet sent to the Local Network Control Block (see RFC 3171)]
        [Severity level: Note]
        [Group: Sequence]
```

I did my homework and found this post here, it explains the exact same problem:
[https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Spotify-doesn-t-play-on-Bose-SoundTouch-anymore/m-p/4962999/highlight/true#M70590](https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Spotify-doesn-t-play-on-Bose-SoundTouch-anymore/m-p/4962999/highlight/true#M70590)

## Proposed changes

It would be nice to edit the TTL and increase a bit the value to allow the packet to hop a few devices.

**Comment by frenck** [comment]
This add-on runs `spotifyd`, which doesn't support that.

Feel free to raise an issue upstream: <https://github.com/Spotifyd/spotifyd>
