### ISSUE TITLE
[WARN] Failed to resolve Access Point: HTTP error

### ISSUE THREAD

**Issue by michaellunzer** [hassio-addons/addon-spotify-connect#7]
# Problem/Motivation
Spotify Connect not running on Ubuntu 18.04 VM (on Proxmox) with USB DAC. 

```
[ERROR] (BCaught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("failed to lookup address information: Temporary failure in name resolution") }
INFO: Starting the Spotify daemon
```
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

I hoped it would work 😄 

## Actual behavior

> (What actually happened)

Log Output: https://ghostbin.com/paste/eefoz

Hassio does not show up as a device on Spotify Connect.

## Steps to reproduce

> (How can someone else make/see it happen)

Run an Ubuntu 18.04 VM with Hass.io on Proxmox
Map the USB DAC to the VM
Run the Spotify Connect plugin
See the error log

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

it seems like the container is having DNS(?) issues because it says failure in Name Resolution ?
Is the container having issues connecting to the internet/spotify for authentication? 
Is it something on my end that I can fix either on the VM or on Proxmox?

**Comment by frenck** [comment]
Seems like you have a DNS issues on your Docker & Ubuntu Bionic (18.04) setup.
This is a common issue with these setups and not really related to the add-on itself.

Try running the following on your host OS as the `root` user:

`echo '{"dns": ["8.8.8.8", "8.8.4.4"]}' > /etc/docker/daemon.json`

Next reboot your system (quickest way).

It should be fixed now.

**Comment by michaellunzer** [comment]
Thanks for your quick reply and assistance! You're right it isn't necessarily related to your plugin, but I appreciate your help -- I will try your solution and close the issue shortly.

Thanks for all you do for the Home-Assistant community! 😃

**Comment by frenck** [comment]
You are welcome sir!
