### ISSUE TITLE
Login through Facebook Account

### ISSUE THREAD

**Issue by nachotp** [hassio-addons/addon-spotify-connect#8]
# Problem/Motivation

> I created my account using facebook (big mistake)  and I don't have a password for spotify.

## Expected behavior

> Login to spotify Connect

## Actual behavior

> Don't have the requested credentials

## Steps to reproduce

> Make a facebook spotify account (?)

## Proposed changes

> Integrate Oauth or client id and client secret just like how home assistant does it.

**Comment by tjorim** [comment]
The client id and secret you proposed is something entirely different. However, there should be a way to log in. You'll need to set a device password: https://www.spotify.com/account/set-device-password/

**Comment by nachotp** [comment]
It works, thank you!
