### ISSUE TITLE
Can't choose USB soundcard

### ISSUE THREAD

**Issue by erikfluff** [hassio-addons/addon-spotify-connect#9]
I just installed latest stable hass.io, 1.9, and installed the connect addon, but i can't choose my usb-soundcard as playback device. it's available as input device

![image](https://user-images.githubusercontent.com/16637063/44619721-57195a80-a88b-11e8-8953-1c92fb1146bf.png)

**Comment by frenck** [comment]
This is not an issue with the add-on, but an issue with Hass.io. So you've reported the issue in the wrong place.

**Comment by frenck** [comment]
Sorry I can't move the issue for you, but you should report this to:

https://github.com/home-assistant/hassio
