### ISSUE TITLE
Cannot get this extension on Raspberry Zero

### ISSUE THREAD

**Issue by enricodeleo** [hassio-addons/addon-spotify-connect#94]
# Problem/Motivation

Cannot install this add-on on Home Assistant OS running on Raspberry Zero.

## Expected behavior

Get Spotify add-on working.

## Actual behavior

Cannot install.

## Steps to reproduce

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/3534555/114634109-28fa1a80-9cc2-11eb-9453-d16739d2b4be.png">

**Comment by sinclairpaul** [comment]
As per the docs https://github.com/hassio-addons/addon-spotify-connect

It isn't available on that platform.

![image](https://user-images.githubusercontent.com/24625998/114634515-b02e9a80-9c90-11eb-8e46-af8f7f849dbf.png)
